import { Hub, User, SyncBatch, AuditLogEntry, APIKey, SyncPage, RAGDocument } from './types';

export const MOCK_HUBS: Hub[] = [
  {
    id: '1',
    name: 'Tâm Đạo Y Quán',
    code: 'tamdao',
    subdomain: 'localhost/tamdao',
    pages: 127,
    users: 12,
    lastUpdate: '2 giờ trước',
    status: 'active',
    pendingSync: 3,
    createdAt: '2024-10-01',
  },
  {
    id: '2',
    name: 'Đỗ Minh Đường',
    code: 'dmd',
    subdomain: 'localhost/dmd',
    pages: 89,
    users: 8,
    lastUpdate: '1 ngày trước',
    status: 'active',
    pendingSync: 0,
    createdAt: '2024-11-15',
  },
  {
    id: '3',
    name: 'HCNS',
    code: 'hcns',
    subdomain: 'localhost/hcns',
    pages: 54,
    users: 15,
    lastUpdate: '3 ngày trước',
    status: 'active',
    pendingSync: 2,
    createdAt: '2024-12-20',
  },
  {
    id: '4',
    name: 'Test Hub',
    code: 'test',
    subdomain: 'localhost/test',
    pages: 0,
    users: 2,
    lastUpdate: '—',
    status: 'inactive',
    pendingSync: 0,
    createdAt: '2025-01-10',
  },
  {
    id: '5',
    name: 'Phòng khám Đa khoa Quốc tế',
    code: 'pkdkqt',
    subdomain: 'localhost/pkdkqt',
    pages: 210,
    users: 25,
    lastUpdate: '5 giờ trước',
    status: 'active',
    pendingSync: 5,
    createdAt: '2024-05-12',
  },
  {
    id: '6',
    name: 'Bệnh viện Y học Cổ truyền',
    code: 'bvyhct',
    subdomain: 'localhost/bvyhct',
    pages: 450,
    users: 60,
    lastUpdate: '10 phút trước',
    status: 'active',
    pendingSync: 12,
    createdAt: '2023-08-20',
  },
  // Plan 03-01 v3.1 Phase 3 FE-04 — ADD hub tdt (Thuốc Dân Tộc — 1 trong 2 hub thật DB)
  // Source: memory/project_real_hubs_deployment.md (dmd Đỗ Minh Đường + tdt Thuốc Dân Tộc)
  {
    id: '7',
    name: 'Thuốc Dân Tộc',
    code: 'tdt',
    subdomain: 'localhost/tdt',
    pages: 178,
    users: 22,
    lastUpdate: '4 giờ trước',
    status: 'active',
    pendingSync: 1,
    createdAt: '2025-01-20',
  },
];

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Nguyễn Văn A', email: 'nva@example.local', role: 'admin', hubId: '1', createdAt: '01/01/2025', lastLogin: '2 giờ trước', status: 'active' },
  { id: 'u2', name: 'Trần Thị B', email: 'ttb@example.local', role: 'viewer', hubId: '1', createdAt: '15/02/2025', lastLogin: 'Chưa đăng nhập', status: 'active' },
  { id: 'u3', name: 'Lê Minh C', email: 'lmc@example.local', role: 'viewer', hubId: '1', createdAt: '10/03/2025', lastLogin: '5 ngày trước', status: 'disabled' },
  { id: 'u4', name: 'Phạm Văn D', email: 'pvd@example.local', role: 'admin', hubId: '2', createdAt: '20/01/2025', lastLogin: '1 giờ trước', status: 'active' },
  { id: 'u5', name: 'Hoàng Thị E', email: 'hte@example.local', role: 'viewer', hubId: '3', createdAt: '05/03/2025', lastLogin: '1 ngày trước', status: 'active' },
  { id: 'u6', name: 'Vũ Đức F', email: 'vdf@example.local', role: 'viewer', hubId: '1', createdAt: '12/01/2025', lastLogin: '3 giờ trước', status: 'active' },
  { id: 'u7', name: 'Đặng Thị G', email: 'dtg@example.local', role: 'admin', hubId: '1', createdAt: '05/01/2025', lastLogin: '30 phút trước', status: 'active' },
  { id: 'u8', name: 'Bùi Văn H', email: 'bvh@example.local', role: 'viewer', hubId: '1', createdAt: '20/02/2025', lastLogin: '2 ngày trước', status: 'active' },
  { id: 'u9', name: 'Ngô Thị I', email: 'nti@example.local', role: 'viewer', hubId: '1', createdAt: '01/03/2025', lastLogin: 'Chưa đăng nhập', status: 'active' },
  { id: 'u10', name: 'Đỗ Văn K', email: 'dvk@example.local', role: 'viewer', hubId: '1', createdAt: '18/02/2025', lastLogin: '1 tuần trước', status: 'disabled' },
  { id: 'u11', name: 'Phan Thị L', email: 'ptl@example.local', role: 'viewer', hubId: '1', createdAt: '22/01/2025', lastLogin: '4 giờ trước', status: 'active' },
  { id: 'u12', name: 'Lý Văn M', email: 'lvm@example.local', role: 'admin', hubId: '1', createdAt: '08/01/2025', lastLogin: '1 giờ trước', status: 'active' },
  { id: 'u13', name: 'Hồ Thị N', email: 'htn@example.local', role: 'viewer', hubId: '1', createdAt: '14/02/2025', lastLogin: '6 giờ trước', status: 'active' },
  { id: 'u14', name: 'Mai Văn O', email: 'mvo@example.local', role: 'viewer', hubId: '1', createdAt: '25/02/2025', lastLogin: '3 ngày trước', status: 'active' },
  { id: 'u15', name: 'Tạ Thị P', email: 'ttp@example.local', role: 'viewer', hubId: '1', createdAt: '03/03/2025', lastLogin: '12 giờ trước', status: 'active' },
  { id: 'u16', name: 'Dương Văn Q', email: 'dvq@example.local', role: 'viewer', hubId: '2', createdAt: '10/01/2025', lastLogin: '2 giờ trước', status: 'active' },
  { id: 'u17', name: 'Lương Thị R', email: 'ltr@example.local', role: 'viewer', hubId: '2', createdAt: '28/01/2025', lastLogin: '5 giờ trước', status: 'active' },
  { id: 'u18', name: 'Cao Văn S', email: 'cvs@example.local', role: 'admin', hubId: '2', createdAt: '15/01/2025', lastLogin: '45 phút trước', status: 'active' },
  { id: 'u19', name: 'Triệu Thị T', email: 'ttt@example.local', role: 'viewer', hubId: '2', createdAt: '05/02/2025', lastLogin: '1 ngày trước', status: 'disabled' },
  { id: 'u20', name: 'Kiều Văn U', email: 'kvu@example.local', role: 'viewer', hubId: '2', createdAt: '12/02/2025', lastLogin: 'Chưa đăng nhập', status: 'active' },
  { id: 'u21', name: 'Tô Thị V', email: 'ttv@example.local', role: 'viewer', hubId: '2', createdAt: '20/02/2025', lastLogin: '8 giờ trước', status: 'active' },
  { id: 'u22', name: 'Châu Văn W', email: 'cvw@example.local', role: 'viewer', hubId: '2', createdAt: '01/03/2025', lastLogin: '2 ngày trước', status: 'active' },
  { id: 'u23', name: 'La Thị X', email: 'ltx@example.local', role: 'viewer', hubId: '3', createdAt: '08/01/2025', lastLogin: '4 giờ trước', status: 'active' },
  { id: 'u24', name: 'Tăng Văn Y', email: 'tvy@example.local', role: 'admin', hubId: '3', createdAt: '15/01/2025', lastLogin: '1 giờ trước', status: 'active' },
  { id: 'u25', name: 'Quách Thị Z', email: 'qtz@example.local', role: 'viewer', hubId: '3', createdAt: '22/01/2025', lastLogin: '3 ngày trước', status: 'active' },
  { id: 'u26', name: 'Trịnh Văn AA', email: 'tvaa@example.local', role: 'viewer', hubId: '3', createdAt: '01/02/2025', lastLogin: '6 giờ trước', status: 'active' },
  { id: 'u27', name: 'Đinh Thị BB', email: 'dtbb@example.local', role: 'viewer', hubId: '3', createdAt: '10/02/2025', lastLogin: 'Chưa đăng nhập', status: 'active' },
  { id: 'u28', name: 'Lâm Văn CC', email: 'lvcc@example.local', role: 'viewer', hubId: '3', createdAt: '18/02/2025', lastLogin: '1 tuần trước', status: 'disabled' },
  { id: 'u29', name: 'Thái Thị DD', email: 'ttdd@example.local', role: 'viewer', hubId: '3', createdAt: '25/02/2025', lastLogin: '5 giờ trước', status: 'active' },
  { id: 'u30', name: 'Mạc Văn EE', email: 'mvee@example.local', role: 'viewer', hubId: '3', createdAt: '05/03/2025', lastLogin: '2 ngày trước', status: 'active' },
  { id: 'u31', name: 'Từ Thị FF', email: 'ttff@example.local', role: 'viewer', hubId: '3', createdAt: '10/03/2025', lastLogin: '10 giờ trước', status: 'active' },
  { id: 'u32', name: 'Hà Văn GG', email: 'hvgg@example.local', role: 'admin', hubId: '3', createdAt: '12/03/2025', lastLogin: '20 phút trước', status: 'active' },
  { id: 'u33', name: 'Sơn Thị HH', email: 'sthh@example.local', role: 'viewer', hubId: '1', createdAt: '15/03/2025', lastLogin: '1 giờ trước', status: 'active' },
  { id: 'u34', name: 'Ông Văn II', email: 'ovii@example.local', role: 'viewer', hubId: '1', createdAt: '18/03/2025', lastLogin: '4 ngày trước', status: 'active' },
  { id: 'u35', name: 'Âu Thị KK', email: 'atkk@example.local', role: 'viewer', hubId: '2', createdAt: '20/03/2025', lastLogin: '7 giờ trước', status: 'active' },
  // v3.1 Phase 3 FE-04 fixture — RBAC hub_admin scope (D-V3.1-Phase3-C LOCKED)
  // Source: .planning/phases/03-frontend-form-refactor/03-CONTEXT.md D-V3.1-Phase3-C
  //         memory/project_real_hubs_deployment.md (dmd Đỗ Minh Đường + tdt Thuốc Dân Tộc 2 hub thật DB)
  { id: 'u-hadmin-dmd', name: 'Nguyễn Hub Admin DMD', email: 'hadmin.dmd@example.local', role: 'hub_admin', hubId: MOCK_HUBS.find(h => h.code === 'dmd')?.id ?? '', createdAt: '01/05/2026', lastLogin: '1 giờ trước', status: 'active' },
  { id: 'u-hadmin-tdt', name: 'Trần Hub Admin TDT', email: 'hadmin.tdt@example.local', role: 'hub_admin', hubId: MOCK_HUBS.find(h => h.code === 'tdt')?.id ?? '', createdAt: '01/05/2026', lastLogin: '30 phút trước', status: 'active' },
];

export const MOCK_SYNC_BATCHES: SyncBatch[] = [
  {
    id: 'b1',
    hubId: '1',
    hubName: 'Tâm Đạo Y Quán',
    pageCount: 8,
    submittedAt: '30 phút trước',
    submittedBy: 'Nguyễn Admin Tâm Đạo',
    status: 'pending',
    filesSummary: { pdf: 3, docx: 2, xlsx: 1, jpg: 1, md: 1 },
    totalSize: '18.5 MB',
  },
  {
    id: 'b2',
    hubId: '3',
    hubName: 'HCNS',
    pageCount: 5,
    submittedAt: '2 giờ trước',
    submittedBy: 'Trần Admin HCNS',
    status: 'pending',
    filesSummary: { docx: 2, xlsx: 2, csv: 1 },
    totalSize: '6.2 MB',
  },
  {
    id: 'b3',
    hubId: '2',
    hubName: 'Đỗ Minh Đường',
    pageCount: 12,
    submittedAt: '3 ngày trước',
    submittedBy: 'Lê Admin DMD',
    status: 'processed',
    processedCount: { approved: 9, rejected: 3 },
    filesSummary: { pdf: 5, docx: 3, pptx: 1, txt: 2, png: 1 },
    totalSize: '45.3 MB',
  },
  { id: 'b4', hubId: '5', hubName: 'Phòng khám Đa khoa Quốc tế', pageCount: 15, submittedAt: '4 giờ trước', submittedBy: 'Trần Quốc Bảo', status: 'pending', filesSummary: { pdf: 6, docx: 4, xlsx: 2, pptx: 1, jpg: 2 }, totalSize: '52.1 MB' },
  { id: 'b5', hubId: '6', hubName: 'Bệnh viện Y học Cổ truyền', pageCount: 22, submittedAt: '5 giờ trước', submittedBy: 'Nguyễn Thị Lan', status: 'pending', filesSummary: { pdf: 10, docx: 5, xlsx: 3, png: 2, md: 2 }, totalSize: '78.6 MB' },
  { id: 'b21', hubId: '2', hubName: 'Đỗ Minh Đường', pageCount: 9, submittedAt: '6 giờ trước', submittedBy: 'Cao Văn S', status: 'pending', filesSummary: { pdf: 4, docx: 3, html: 2 }, totalSize: '22.4 MB' },
  { id: 'b22', hubId: '1', hubName: 'Tâm Đạo Y Quán', pageCount: 4, submittedAt: '7 giờ trước', submittedBy: 'Vũ Đức F', status: 'pending', filesSummary: { pdf: 2, jpg: 1, txt: 1 }, totalSize: '8.7 MB' },
  { id: 'b23', hubId: '3', hubName: 'HCNS', pageCount: 11, submittedAt: '8 giờ trước', submittedBy: 'Hoàng Thị E', status: 'pending', filesSummary: { xlsx: 4, csv: 3, docx: 2, pdf: 2 }, totalSize: '15.3 MB' },
  { id: 'b24', hubId: '6', hubName: 'Bệnh viện Y học Cổ truyền', pageCount: 7, submittedAt: '10 giờ trước', submittedBy: 'Phạm Minh Tuấn', status: 'pending', filesSummary: { pdf: 3, docx: 2, png: 2 }, totalSize: '31.2 MB' },
  { id: 'b25', hubId: '5', hubName: 'Phòng khám Đa khoa Quốc tế', pageCount: 3, submittedAt: '12 giờ trước', submittedBy: 'Lê Văn Hùng', status: 'pending', filesSummary: { pptx: 1, pdf: 1, docx: 1 }, totalSize: '14.8 MB' },
  { id: 'b26', hubId: '2', hubName: 'Đỗ Minh Đường', pageCount: 14, submittedAt: '14 giờ trước', submittedBy: 'Lê Admin DMD', status: 'pending', filesSummary: { pdf: 6, docx: 3, md: 2, txt: 2, csv: 1 }, totalSize: '38.9 MB' },
  { id: 'b27', hubId: '1', hubName: 'Tâm Đạo Y Quán', pageCount: 6, submittedAt: '16 giờ trước', submittedBy: 'Đặng Thị G', status: 'pending', filesSummary: { pdf: 2, docx: 2, xlsx: 1, jpg: 1 }, totalSize: '12.1 MB' },
  { id: 'b28', hubId: '3', hubName: 'HCNS', pageCount: 18, submittedAt: '18 giờ trước', submittedBy: 'Tăng Văn Y', status: 'pending', filesSummary: { xlsx: 6, csv: 4, docx: 4, pdf: 3, pptx: 1 }, totalSize: '28.7 MB' },
  { id: 'b6', hubId: '1', hubName: 'Tâm Đạo Y Quán', pageCount: 3, submittedAt: '1 ngày trước', submittedBy: 'Nguyễn Admin Tâm Đạo', status: 'processed', processedCount: { approved: 3, rejected: 0 }, filesSummary: { pdf: 2, docx: 1 }, totalSize: '5.4 MB' },
  { id: 'b7', hubId: '3', hubName: 'HCNS', pageCount: 7, submittedAt: '1 ngày trước', submittedBy: 'Trần Admin HCNS', status: 'processed', processedCount: { approved: 5, rejected: 2 }, filesSummary: { xlsx: 3, docx: 2, csv: 1, pdf: 1 }, totalSize: '9.8 MB' },
  { id: 'b8', hubId: '5', hubName: 'Phòng khám Đa khoa Quốc tế', pageCount: 10, submittedAt: '2 ngày trước', submittedBy: 'Lê Văn Hùng', status: 'processed', processedCount: { approved: 8, rejected: 2 }, filesSummary: { pdf: 4, docx: 3, pptx: 1, jpg: 1, xlsx: 1 }, totalSize: '34.5 MB' },
  { id: 'b9', hubId: '6', hubName: 'Bệnh viện Y học Cổ truyền', pageCount: 18, submittedAt: '2 ngày trước', submittedBy: 'Phạm Minh Tuấn', status: 'processed', processedCount: { approved: 15, rejected: 3 }, filesSummary: { pdf: 8, docx: 4, xlsx: 3, png: 2, md: 1 }, totalSize: '67.2 MB' },
  { id: 'b10', hubId: '2', hubName: 'Đỗ Minh Đường', pageCount: 6, submittedAt: '3 ngày trước', submittedBy: 'Lê Admin DMD', status: 'processed', processedCount: { approved: 6, rejected: 0 }, filesSummary: { pdf: 3, docx: 2, txt: 1 }, totalSize: '11.6 MB' },
  { id: 'b11', hubId: '1', hubName: 'Tâm Đạo Y Quán', pageCount: 4, submittedAt: '4 ngày trước', submittedBy: 'Vũ Đức F', status: 'processed', processedCount: { approved: 2, rejected: 2 }, filesSummary: { pdf: 2, html: 1, md: 1 }, totalSize: '7.3 MB' },
  { id: 'b12', hubId: '3', hubName: 'HCNS', pageCount: 9, submittedAt: '4 ngày trước', submittedBy: 'Hoàng Thị E', status: 'processed', processedCount: { approved: 7, rejected: 2 }, filesSummary: { xlsx: 3, csv: 2, docx: 2, pdf: 2 }, totalSize: '14.1 MB' },
  { id: 'b13', hubId: '6', hubName: 'Bệnh viện Y học Cổ truyền', pageCount: 14, submittedAt: '5 ngày trước', submittedBy: 'Nguyễn Thị Lan', status: 'processed', processedCount: { approved: 12, rejected: 2 }, filesSummary: { pdf: 6, docx: 4, png: 2, xlsx: 2 }, totalSize: '48.9 MB' },
  { id: 'b14', hubId: '5', hubName: 'Phòng khám Đa khoa Quốc tế', pageCount: 8, submittedAt: '5 ngày trước', submittedBy: 'Trần Quốc Bảo', status: 'processed', processedCount: { approved: 8, rejected: 0 }, filesSummary: { pdf: 3, docx: 2, pptx: 2, xlsx: 1 }, totalSize: '29.4 MB' },
  { id: 'b15', hubId: '2', hubName: 'Đỗ Minh Đường', pageCount: 11, submittedAt: '6 ngày trước', submittedBy: 'Cao Văn S', status: 'processed', processedCount: { approved: 9, rejected: 2 }, filesSummary: { pdf: 5, docx: 3, md: 2, txt: 1 }, totalSize: '24.7 MB' },
  { id: 'b16', hubId: '1', hubName: 'Tâm Đạo Y Quán', pageCount: 5, submittedAt: '1 tuần trước', submittedBy: 'Đặng Thị G', status: 'processed', processedCount: { approved: 4, rejected: 1 }, filesSummary: { pdf: 2, docx: 1, jpg: 1, xlsx: 1 }, totalSize: '13.5 MB' },
  { id: 'b17', hubId: '3', hubName: 'HCNS', pageCount: 13, submittedAt: '1 tuần trước', submittedBy: 'Tăng Văn Y', status: 'processed', processedCount: { approved: 10, rejected: 3 }, filesSummary: { xlsx: 5, docx: 3, csv: 3, pdf: 2 }, totalSize: '19.2 MB' },
  { id: 'b18', hubId: '6', hubName: 'Bệnh viện Y học Cổ truyền', pageCount: 20, submittedAt: '1 tuần trước', submittedBy: 'Phạm Minh Tuấn', status: 'processed', processedCount: { approved: 17, rejected: 3 }, filesSummary: { pdf: 9, docx: 5, xlsx: 3, png: 2, pptx: 1 }, totalSize: '82.1 MB' },
  { id: 'b19', hubId: '5', hubName: 'Phòng khám Đa khoa Quốc tế', pageCount: 7, submittedAt: '8 ngày trước', submittedBy: 'Lê Văn Hùng', status: 'processed', processedCount: { approved: 5, rejected: 2 }, filesSummary: { pdf: 3, docx: 2, jpg: 1, html: 1 }, totalSize: '21.8 MB' },
  { id: 'b20', hubId: '2', hubName: 'Đỗ Minh Đường', pageCount: 16, submittedAt: '9 ngày trước', submittedBy: 'Lê Admin DMD', status: 'processed', processedCount: { approved: 14, rejected: 2 }, filesSummary: { pdf: 7, docx: 4, md: 2, txt: 2, csv: 1 }, totalSize: '41.6 MB' },
];

export const MOCK_SYNC_PAGES: SyncPage[] = [
  {
    id: 'p1',
    batchId: 'b1',
    title: 'Phác đồ trị đau dạ dày',
    fileName: 'Phac-do-tri-dau-da-day-2025.pdf',
    fileType: 'pdf',
    fileSize: '3.2 MB',
    category: 'Điều trị',
    tags: ['Dạ dày', 'Đông y'],
    content: '# Phác đồ trị đau dạ dày\n\nNội dung chi tiết về phác đồ chữa đau dạ dày bằng Đông y, tập trung vào các vị thảo dược tự nhiên và chế độ ăn uống sinh hoạt điều độ.',
    author: 'Nguyễn Văn A',
    createdAt: '2025-03-14',
    status: 'pending',
    similarityScore: 0.87,
    similarPageTitle: 'Quy trình chữa dạ dày',
  },
  {
    id: 'p2',
    batchId: 'b1',
    title: 'Quy trình onboarding nhân viên mới',
    fileName: 'Quy-trinh-onboarding-2025.docx',
    fileType: 'docx',
    fileSize: '1.8 MB',
    category: 'Vận hành',
    tags: ['Nhân sự', 'Quy trình'],
    content: '# Quy trình onboarding\n\nCác bước thực hiện khi có nhân viên mới gia nhập công ty, bao gồm chuẩn bị trang thiết bị, tài khoản và đào tạo hội nhập.',
    author: 'Trần Thị B',
    createdAt: '2025-03-14',
    status: 'pending',
  },
  {
    id: 'p3',
    batchId: 'b1',
    title: 'Bảng theo dõi tồn kho dược liệu tháng 3',
    fileName: 'Ton-kho-duoc-lieu-T3-2025.xlsx',
    fileType: 'xlsx',
    fileSize: '2.1 MB',
    category: 'Kho vận',
    tags: ['Dược liệu', 'Tồn kho'],
    content: '# Bảng tồn kho dược liệu\n\nDanh sách chi tiết các vị thuốc, số lượng tồn, hạn sử dụng và nhà cung cấp.',
    author: 'Nguyễn Văn A',
    createdAt: '2025-03-14',
    status: 'pending',
  },
  {
    id: 'p4',
    batchId: 'b1',
    title: 'Ảnh chụp bằng cấp chứng chỉ hành nghề',
    fileName: 'Chung-chi-hanh-nghe-BS-Nguyen.jpg',
    fileType: 'jpg',
    fileSize: '4.5 MB',
    category: 'Hồ sơ',
    tags: ['Chứng chỉ', 'Nhân sự'],
    content: '# Chứng chỉ hành nghề\n\nẢnh chụp scan bằng cấp và chứng chỉ hành nghề của BS. Nguyễn Văn A.',
    author: 'Nguyễn Văn A',
    createdAt: '2025-03-14',
    status: 'pending',
  },
  {
    id: 'p5',
    batchId: 'b1',
    title: 'Ghi chú nghiên cứu bài thuốc cổ phương',
    fileName: 'Ghi-chu-bai-thuoc-co-phuong.md',
    fileType: 'md',
    fileSize: '45 KB',
    category: 'Nghiên cứu',
    tags: ['Cổ phương', 'Thảo dược'],
    content: '# Ghi chú bài thuốc cổ phương\n\n## Bài Tứ quân tử thang\n- Nhân sâm 10g\n- Bạch truật 10g\n- Phục linh 10g\n- Cam thảo 5g\n\nCông dụng: Bổ khí kiện tỳ, dùng cho trường hợp tỳ vị hư nhược.',
    author: 'Trần Thị B',
    createdAt: '2025-03-14',
    status: 'pending',
  },
  {
    id: 'p6',
    batchId: 'b1',
    title: 'Phác đồ điều trị viêm khớp dạng thấp',
    fileName: 'Phac-do-viem-khop-dang-thap.pdf',
    fileType: 'pdf',
    fileSize: '2.8 MB',
    category: 'Điều trị',
    tags: ['Xương khớp', 'Đông y'],
    content: '# Phác đồ viêm khớp dạng thấp\n\nKết hợp châm cứu, xoa bóp bấm huyệt và thuốc thang trong điều trị viêm khớp dạng thấp.',
    author: 'Nguyễn Văn A',
    createdAt: '2025-03-14',
    status: 'pending',
  },
  {
    id: 'p7',
    batchId: 'b1',
    title: 'Hướng dẫn vệ sinh phòng khám Đông y',
    fileName: 'HD-ve-sinh-phong-kham.docx',
    fileType: 'docx',
    fileSize: '890 KB',
    category: 'Vận hành',
    tags: ['Vệ sinh', 'An toàn'],
    content: '# Hướng dẫn vệ sinh phòng khám\n\nQuy trình vệ sinh hàng ngày, tuần và tháng cho các phòng điều trị, phòng thuốc và khu vực tiếp đón.',
    author: 'Trần Thị B',
    createdAt: '2025-03-14',
    status: 'pending',
  },
  {
    id: 'p8',
    batchId: 'b1',
    title: 'Phác đồ châm cứu huyệt Hợp Cốc',
    fileName: 'Phac-do-cham-cuu-Hop-Coc.pdf',
    fileType: 'pdf',
    fileSize: '1.5 MB',
    category: 'Điều trị',
    tags: ['Châm cứu', 'Huyệt đạo'],
    content: '# Châm cứu huyệt Hợp Cốc\n\nVị trí: Giữa xương bàn tay 1 và 2. Công dụng: Giảm đau đầu, đau răng, cảm cúm. Kỹ thuật châm và lưu kim.',
    author: 'Nguyễn Văn A',
    createdAt: '2025-03-14',
    status: 'pending',
  },
  {
    id: 'p9',
    batchId: 'b3',
    title: 'Bài thuốc trị mất ngủ kinh niên',
    fileName: 'Bai-thuoc-tri-mat-ngu.pdf',
    fileType: 'pdf',
    fileSize: '2.4 MB',
    category: 'Điều trị',
    tags: ['Mất ngủ', 'Thảo dược'],
    content: '# Bài thuốc trị mất ngủ\n\nSử dụng tâm sen, lạc tiên và các vị thuốc an thần khác để giúp bệnh nhân có giấc ngủ sâu và tự nhiên.',
    author: 'Lê Admin DMD',
    createdAt: '2025-03-10',
    status: 'approved',
  },
  {
    id: 'p10',
    batchId: 'b3',
    title: 'Chính sách bảo mật dữ liệu khách hàng',
    fileName: 'Chinh-sach-bao-mat-DLKH.docx',
    fileType: 'docx',
    fileSize: '1.2 MB',
    category: 'Vận hành',
    tags: ['Bảo mật', 'Pháp lý'],
    content: '# Chính sách bảo mật\n\nQuy định về việc thu thập, lưu trữ và sử dụng thông tin cá nhân của khách hàng tại phòng khám.',
    author: 'Lê Admin DMD',
    createdAt: '2025-03-10',
    status: 'rejected',
    rejectionReason: 'Nội dung chưa đầy đủ các điều khoản theo quy định mới của Bộ Y tế.',
  },
  {
    id: 'p11',
    batchId: 'b3',
    title: 'Hướng dẫn sử dụng máy đo huyết áp',
    fileName: 'HD-su-dung-may-do-huyet-ap.pdf',
    fileType: 'pdf',
    fileSize: '3.1 MB',
    category: 'Thiết bị',
    tags: ['Hướng dẫn', 'Y tế'],
    content: '# Hướng dẫn sử dụng máy đo huyết áp\n\nCác bước vận hành máy đo huyết áp điện tử tại nhà cho bệnh nhân.',
    author: 'Lê Admin DMD',
    createdAt: '2025-03-11',
    status: 'approved',
  },
  {
    id: 'p12',
    batchId: 'b3',
    title: 'Trình bày kết quả nghiên cứu lâm sàng Q1',
    fileName: 'Ket-qua-nghien-cuu-lam-sang-Q1.pptx',
    fileType: 'pptx',
    fileSize: '15.6 MB',
    category: 'Nghiên cứu',
    tags: ['Nghiên cứu', 'Lâm sàng'],
    content: '# Kết quả nghiên cứu lâm sàng Q1\n\nTổng hợp kết quả thử nghiệm lâm sàng trên 150 bệnh nhân sử dụng phác đồ Đông - Tây y kết hợp.',
    author: 'Lê Admin DMD',
    createdAt: '2025-03-10',
    status: 'approved',
  },
  {
    id: 'p13',
    batchId: 'b3',
    title: 'Hình chụp cây thuốc nam Đỗ Minh Đường',
    fileName: 'Hinh-cay-thuoc-nam-DMD.png',
    fileType: 'png',
    fileSize: '8.2 MB',
    category: 'Dược liệu',
    tags: ['Thuốc nam', 'Hình ảnh'],
    content: '# Hình chụp cây thuốc nam\n\nBộ sưu tập ảnh chụp các loại cây thuốc nam được trồng trong vườn dược liệu Đỗ Minh Đường.',
    author: 'Lê Admin DMD',
    createdAt: '2025-03-11',
    status: 'approved',
  },
  {
    id: 'p14',
    batchId: 'b3',
    title: 'Ghi chép kinh nghiệm chữa bệnh gút',
    fileName: 'Kinh-nghiem-chua-benh-gut.txt',
    fileType: 'txt',
    fileSize: '28 KB',
    category: 'Điều trị',
    tags: ['Gút', 'Kinh nghiệm'],
    content: '# Kinh nghiệm chữa bệnh gút\n\nTổng hợp các bài thuốc và phương pháp điều trị bệnh gút theo y học cổ truyền đã áp dụng thành công.',
    author: 'Lê Admin DMD',
    createdAt: '2025-03-10',
    status: 'approved',
  },
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  { id: 'l1', timestamp: '14/03/2025 09:15:22', user: 'Nguyễn Văn A', isAI: false, action: 'UPDATE', target: '"Phác đồ trị đau dạ dày"', hub: 'Đỗ Minh Đường', ip: '192.168.1.1' },
  { id: 'l2', timestamp: '14/03/2025 09:08:11', user: 'Claude Desktop', isAI: true, action: 'MCP_WRITE', target: '"Quy trình onboarding"', hub: 'HCNS', ip: 'api' },
  { id: 'l3', timestamp: '14/03/2025 08:55:04', user: 'Trần Thị B', isAI: false, action: 'SYNC', target: '—', hub: 'Tâm Đạo', ip: '192.168.1.5' },
  { id: 'l4', timestamp: '14/03/2025 08:42:15', user: 'Phạm Văn D', isAI: false, action: 'CREATE', target: '"Hướng dẫn sử dụng thuốc nam"', hub: 'Đỗ Minh Đường', ip: '192.168.1.8' },
  { id: 'l5', timestamp: '14/03/2025 08:30:00', user: 'Gemini Agent', isAI: true, action: 'MCP_READ', target: '"Danh mục dược liệu"', hub: 'Tâm Đạo', ip: 'api' },
  { id: 'l6', timestamp: '14/03/2025 08:15:33', user: 'Hoàng Thị E', isAI: false, action: 'UPDATE', target: '"Chính sách nghỉ phép 2025"', hub: 'HCNS', ip: '192.168.1.12' },
  { id: 'l7', timestamp: '14/03/2025 07:58:41', user: 'Lê Minh C', isAI: false, action: 'LOGIN', target: '—', hub: 'Tâm Đạo', ip: '10.0.0.5' },
  { id: 'l8', timestamp: '14/03/2025 07:45:19', user: 'Claude Desktop', isAI: true, action: 'MCP_WRITE', target: '"Báo cáo tổng hợp Q1"', hub: 'HCNS', ip: 'api' },
  { id: 'l9', timestamp: '13/03/2025 17:30:05', user: 'Nguyễn Văn A', isAI: false, action: 'APPROVE_SYNC', target: 'Batch #b3 (12 trang)', hub: 'Đỗ Minh Đường', ip: '192.168.1.1' },
  { id: 'l10', timestamp: '13/03/2025 17:15:22', user: 'Vũ Đức F', isAI: false, action: 'CREATE', target: '"Phác đồ xương khớp mới"', hub: 'Tâm Đạo', ip: '192.168.1.20' },
  { id: 'l11', timestamp: '13/03/2025 16:50:10', user: 'Đặng Thị G', isAI: false, action: 'UPDATE', target: '"Quy trình khám bệnh 2024"', hub: 'Tâm Đạo', ip: '192.168.1.22' },
  { id: 'l12', timestamp: '13/03/2025 16:30:45', user: 'Gemini Agent', isAI: true, action: 'MCP_READ', target: '"Bảng giá dịch vụ"', hub: 'Đỗ Minh Đường', ip: 'api' },
  { id: 'l13', timestamp: '13/03/2025 15:55:33', user: 'Bùi Văn H', isAI: false, action: 'CREATE', target: '"Biên bản họp tuần 11"', hub: 'Tâm Đạo', ip: '192.168.1.25' },
  { id: 'l14', timestamp: '13/03/2025 15:20:18', user: 'Phạm Văn D', isAI: false, action: 'DELETE', target: '"Tài liệu test cũ"', hub: 'Đỗ Minh Đường', ip: '192.168.1.8' },
  { id: 'l15', timestamp: '13/03/2025 14:45:00', user: 'Claude Desktop', isAI: true, action: 'MCP_WRITE', target: '"Tổng hợp phác đồ điều trị"', hub: 'Tâm Đạo', ip: 'api' },
  { id: 'l16', timestamp: '13/03/2025 14:10:27', user: 'Hoàng Thị E', isAI: false, action: 'UPDATE', target: '"Danh sách nhân viên mới"', hub: 'HCNS', ip: '192.168.1.12' },
  { id: 'l17', timestamp: '13/03/2025 13:35:44', user: 'Ngô Thị I', isAI: false, action: 'LOGIN', target: '—', hub: 'Tâm Đạo', ip: '10.0.0.15' },
  { id: 'l18', timestamp: '13/03/2025 11:20:30', user: 'Dương Văn Q', isAI: false, action: 'CREATE', target: '"Hướng dẫn sơ cứu cập nhật"', hub: 'Đỗ Minh Đường', ip: '192.168.1.30' },
  { id: 'l19', timestamp: '13/03/2025 10:55:12', user: 'Gemini Agent', isAI: true, action: 'MCP_READ', target: '"Quy trình vận hành"', hub: 'HCNS', ip: 'api' },
  { id: 'l20', timestamp: '13/03/2025 10:30:00', user: 'Lương Thị R', isAI: false, action: 'UPDATE', target: '"Bảng lương tháng 2"', hub: 'Đỗ Minh Đường', ip: '192.168.1.32' },
  { id: 'l21', timestamp: '13/03/2025 09:45:18', user: 'Cao Văn S', isAI: false, action: 'APPROVE_SYNC', target: 'Batch #b2 (5 trang)', hub: 'HCNS', ip: '192.168.1.35' },
  { id: 'l22', timestamp: '13/03/2025 09:15:40', user: 'Claude Desktop', isAI: true, action: 'MCP_WRITE', target: '"Phân tích dữ liệu bệnh nhân"', hub: 'Tâm Đạo', ip: 'api' },
  { id: 'l23', timestamp: '12/03/2025 17:40:22', user: 'Triệu Thị T', isAI: false, action: 'CREATE', target: '"Kế hoạch truyền thông Q2"', hub: 'Đỗ Minh Đường', ip: '192.168.1.38' },
  { id: 'l24', timestamp: '12/03/2025 16:55:05', user: 'Phan Thị L', isAI: false, action: 'UPDATE', target: '"Nội quy phòng khám"', hub: 'Tâm Đạo', ip: '192.168.1.40' },
  { id: 'l25', timestamp: '12/03/2025 16:10:33', user: 'Gemini Agent', isAI: true, action: 'MCP_READ', target: '"Báo cáo tài chính Q1"', hub: 'HCNS', ip: 'api' },
  { id: 'l26', timestamp: '12/03/2025 15:25:18', user: 'Lý Văn M', isAI: false, action: 'REJECT_SYNC', target: 'Trang "Chính sách cũ"', hub: 'Tâm Đạo', ip: '192.168.1.1' },
  { id: 'l27', timestamp: '12/03/2025 14:50:44', user: 'Hồ Thị N', isAI: false, action: 'CREATE', target: '"Hướng dẫn vệ sinh phòng mổ"', hub: 'Tâm Đạo', ip: '192.168.1.42' },
  { id: 'l28', timestamp: '12/03/2025 14:05:12', user: 'Claude Desktop', isAI: true, action: 'MCP_WRITE', target: '"Cập nhật danh mục thuốc"', hub: 'Đỗ Minh Đường', ip: 'api' },
  { id: 'l29', timestamp: '12/03/2025 13:20:30', user: 'Mai Văn O', isAI: false, action: 'UPDATE', target: '"Quy trình xử lý rác thải"', hub: 'Tâm Đạo', ip: '192.168.1.45' },
  { id: 'l30', timestamp: '12/03/2025 12:35:00', user: 'La Thị X', isAI: false, action: 'SYNC', target: '—', hub: 'HCNS', ip: '192.168.1.48' },
  { id: 'l31', timestamp: '12/03/2025 11:50:25', user: 'Tăng Văn Y', isAI: false, action: 'CREATE', target: '"Kế hoạch đào tạo Q2"', hub: 'HCNS', ip: '192.168.1.50' },
  { id: 'l32', timestamp: '12/03/2025 11:05:18', user: 'Gemini Agent', isAI: true, action: 'MCP_READ', target: '"Phác đồ trị viêm họng"', hub: 'Tâm Đạo', ip: 'api' },
  { id: 'l33', timestamp: '12/03/2025 10:20:40', user: 'Quách Thị Z', isAI: false, action: 'UPDATE', target: '"Chính sách nghỉ phép"', hub: 'HCNS', ip: '192.168.1.52' },
  { id: 'l34', timestamp: '12/03/2025 09:35:15', user: 'Trịnh Văn AA', isAI: false, action: 'LOGIN', target: '—', hub: 'HCNS', ip: '10.0.0.22' },
  { id: 'l35', timestamp: '11/03/2025 17:50:30', user: 'Đinh Thị BB', isAI: false, action: 'CREATE', target: '"Biên bản kiểm kê Q1"', hub: 'HCNS', ip: '192.168.1.55' },
];

export const MOCK_RAG_CONFIGS = [
  { id: 'rag-1', name: 'Default (Gemini 2.0)' },
  { id: 'rag-2', name: 'High Precision (Text-004)' },
  { id: 'rag-3', name: 'Fast Retrieval (ChromaDB)' },
];

export const MOCK_API_KEYS: APIKey[] = [
  { id: 'k1', name: 'Claude Desktop — Team AI', permissions: ['Read', 'Write'], allowedHubs: ['Tất cả Hub'], allowedRAGConfigs: ['Default (Gemini 2.0)', 'High Precision (Text-004)'], createdAt: '01/01/2025', lastUsed: '5 phút trước', requests7d: 1247, requestsToday: 156, bandwidthUsed: '12.4 MB', rateLimit: 100, status: 'active' },
  { id: 'k2', name: 'ChatGPT Plugin', permissions: ['Read'], allowedHubs: ['Tâm Đạo', 'DMD'], allowedRAGConfigs: ['Default (Gemini 2.0)'], createdAt: '15/02/2025', lastUsed: '2 ngày trước', requests7d: 89, requestsToday: 12, bandwidthUsed: '1.2 MB', rateLimit: 50, status: 'active' },
  { id: 'k3', name: 'Test Key cũ', permissions: ['Read'], allowedHubs: ['HCNS'], allowedRAGConfigs: [], createdAt: '10/03/2025', lastUsed: '30 ngày trước', requests7d: 0, requestsToday: 0, bandwidthUsed: '0 KB', rateLimit: 10, status: 'revoked' },
  { id: 'k4', name: 'Gemini Agent — Tâm Đạo', permissions: ['Read', 'Write'], allowedHubs: ['Tâm Đạo'], allowedRAGConfigs: ['Default (Gemini 2.0)'], createdAt: '05/01/2025', lastUsed: '10 phút trước', requests7d: 2340, requestsToday: 312, bandwidthUsed: '28.1 MB', rateLimit: 200, status: 'active' },
  { id: 'k5', name: 'Mobile App — iOS', permissions: ['Read'], allowedHubs: ['Tất cả Hub'], allowedRAGConfigs: ['Fast Retrieval (ChromaDB)'], createdAt: '20/01/2025', lastUsed: '1 giờ trước', requests7d: 567, requestsToday: 78, bandwidthUsed: '5.6 MB', rateLimit: 100, status: 'active' },
  { id: 'k6', name: 'Mobile App — Android', permissions: ['Read'], allowedHubs: ['Tất cả Hub'], allowedRAGConfigs: ['Fast Retrieval (ChromaDB)'], createdAt: '20/01/2025', lastUsed: '30 phút trước', requests7d: 432, requestsToday: 65, bandwidthUsed: '4.3 MB', rateLimit: 100, status: 'active' },
  { id: 'k7', name: 'Webhook — Slack Bot', permissions: ['Read'], allowedHubs: ['HCNS'], allowedRAGConfigs: ['Default (Gemini 2.0)'], createdAt: '01/02/2025', lastUsed: '3 giờ trước', requests7d: 156, requestsToday: 23, bandwidthUsed: '890 KB', rateLimit: 30, status: 'active' },
  { id: 'k8', name: 'Data Pipeline — ETL', permissions: ['Read', 'Write'], allowedHubs: ['Tất cả Hub'], allowedRAGConfigs: ['High Precision (Text-004)'], createdAt: '10/02/2025', lastUsed: '6 giờ trước', requests7d: 890, requestsToday: 0, bandwidthUsed: '45.2 MB', rateLimit: 500, status: 'active' },
  { id: 'k9', name: 'Perplexity Integration', permissions: ['Read'], allowedHubs: ['Tâm Đạo', 'DMD'], allowedRAGConfigs: ['Default (Gemini 2.0)'], createdAt: '15/02/2025', lastUsed: '1 ngày trước', requests7d: 234, requestsToday: 0, bandwidthUsed: '2.1 MB', rateLimit: 50, status: 'active' },
  { id: 'k10', name: 'Copilot Extension', permissions: ['Read', 'Write'], allowedHubs: ['HCNS'], allowedRAGConfigs: ['Default (Gemini 2.0)', 'High Precision (Text-004)'], createdAt: '20/02/2025', lastUsed: '4 giờ trước', requests7d: 345, requestsToday: 45, bandwidthUsed: '3.4 MB', rateLimit: 100, status: 'active' },
  { id: 'k11', name: 'Dev Key — Staging', permissions: ['Read', 'Write'], allowedHubs: ['Tất cả Hub'], allowedRAGConfigs: ['Default (Gemini 2.0)', 'Fast Retrieval (ChromaDB)'], createdAt: '25/02/2025', lastUsed: '2 ngày trước', requests7d: 45, requestsToday: 0, bandwidthUsed: '320 KB', rateLimit: 20, status: 'active' },
  { id: 'k12', name: 'Old Migration Key', permissions: ['Read'], allowedHubs: ['DMD'], allowedRAGConfigs: [], createdAt: '01/12/2024', lastUsed: '60 ngày trước', requests7d: 0, requestsToday: 0, bandwidthUsed: '0 KB', rateLimit: 10, status: 'revoked' },
  { id: 'k13', name: 'Backup Service', permissions: ['Read'], allowedHubs: ['Tất cả Hub'], allowedRAGConfigs: ['High Precision (Text-004)'], createdAt: '01/03/2025', lastUsed: '12 giờ trước', requests7d: 168, requestsToday: 24, bandwidthUsed: '67.8 MB', rateLimit: 50, status: 'active' },
  { id: 'k14', name: 'Analytics Dashboard', permissions: ['Read'], allowedHubs: ['Tất cả Hub'], allowedRAGConfigs: ['Fast Retrieval (ChromaDB)'], createdAt: '05/03/2025', lastUsed: '2 giờ trước', requests7d: 1120, requestsToday: 189, bandwidthUsed: '8.9 MB', rateLimit: 200, status: 'active' },
  { id: 'k15', name: 'Temp Key — Demo', permissions: ['Read'], allowedHubs: ['Tâm Đạo'], allowedRAGConfigs: [], createdAt: '08/03/2025', lastUsed: '5 ngày trước', requests7d: 12, requestsToday: 0, bandwidthUsed: '56 KB', rateLimit: 10, status: 'revoked' },
];

export const MOCK_DOCUMENTS: RAGDocument[] = [
  {
    id: 'doc-1',
    name: 'Quy-trinh-kham-benh-2024.pdf',
    type: 'pdf',
    size: '2.4 MB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-20T10:00:00Z',
    uploadedBy: 'Admin',
    content: 'Quy trình khám bệnh 2024 bao gồm các bước: 1. Đăng ký tại quầy. 2. Khám lâm sàng. 3. Xét nghiệm (nếu có). 4. Nhận kết luận và đơn thuốc. 5. Thanh toán và nhận thuốc tại quầy dược.',
  },
  {
    id: 'doc-2',
    name: 'Huong-dan-su-dung-thuoc.docx',
    type: 'docx',
    size: '1.1 MB',
    hubId: '2',
    status: 'processing',
    progress: 45,
    uploadedAt: '2024-03-21T14:30:00Z',
    uploadedBy: 'Admin',
    content: 'Hướng dẫn sử dụng thuốc: Uống sau khi ăn 30 phút. Không dùng chung với rượu bia. Bảo quản nơi khô ráo, thoáng mát.',
  },
  {
    id: 'doc-3',
    name: 'Chinh-sach-bao-mat.txt',
    type: 'txt',
    size: '15 KB',
    hubId: '1',
    status: 'pending',
    progress: 0,
    uploadedAt: '2024-03-21T16:00:00Z',
    uploadedBy: 'Admin',
    content: 'Chính sách bảo mật: Chúng tôi cam kết bảo vệ thông tin cá nhân của bệnh nhân theo đúng quy định của pháp luật.',
  },
  {
    id: 'doc-4',
    name: 'Bao-cao-tai-chinh-Q1-2024.xlsx',
    type: 'xlsx',
    size: '4.5 MB',
    hubId: '3',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-22T09:00:00Z',
    uploadedBy: 'Kế toán',
    content: 'Báo cáo tài chính quý 1 năm 2024 cho thấy doanh thu tăng trưởng 15% so với cùng kỳ năm ngoái.',
  },
  {
    id: 'doc-5',
    name: 'Danh-muc-thuoc-thiet-yeu.pdf',
    type: 'pdf',
    size: '3.2 MB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-22T11:30:00Z',
    uploadedBy: 'Dược sĩ',
    content: 'Danh mục thuốc thiết yếu bao gồm các loại thuốc cơ bản cần có tại phòng khám.',
  },
  {
    id: 'doc-6',
    name: 'Quy-dinh-ve-an-toan-lao-dong.docx',
    type: 'docx',
    size: '850 KB',
    hubId: '3',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-23T08:15:00Z',
    uploadedBy: 'Nhân sự',
    content: 'Quy định về an toàn lao động nhằm đảm bảo môi trường làm việc an toàn cho nhân viên.',
  },
  {
    id: 'doc-7',
    name: 'Ke-hoach-marketing-2024.pptx',
    type: 'pptx',
    size: '12.4 MB',
    hubId: '2',
    status: 'processing',
    progress: 70,
    uploadedAt: '2024-03-23T15:45:00Z',
    uploadedBy: 'Marketing',
    content: 'Kế hoạch marketing năm 2024 tập trung vào việc phát triển thương hiệu trên các nền tảng số.',
  },
  {
    id: 'doc-8',
    name: 'Bien-ban-hop-giao-ban-tuan-12.txt',
    type: 'txt',
    size: '12 KB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-24T10:30:00Z',
    uploadedBy: 'Thư ký',
    content: 'Biên bản họp giao ban tuần 12 ghi lại các nội dung thảo luận và phân công công việc.',
  },
  {
    id: 'doc-9',
    name: 'Huong-dan-so-cuu-co-ban.pdf',
    type: 'pdf',
    size: '5.6 MB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-24T14:00:00Z',
    uploadedBy: 'Bác sĩ',
    content: 'Hướng dẫn sơ cứu cơ bản cung cấp các kiến thức cần thiết để xử lý các tình huống khẩn cấp.',
  },
  {
    id: 'doc-10',
    name: 'Quy-trinh-tiep-nhan-benh-nhan.docx',
    type: 'docx',
    size: '1.2 MB',
    hubId: '2',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-25T09:30:00Z',
    uploadedBy: 'Lễ tân',
    content: 'Quy trình tiếp nhận bệnh nhân giúp chuẩn hóa việc đón tiếp và đăng ký khám chữa bệnh.',
  },
  {
    id: 'doc-11',
    name: 'Bao-cao-nghien-cuu-thi-truong.pdf',
    type: 'pdf',
    size: '8.4 MB',
    hubId: '2',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-25T16:20:00Z',
    uploadedBy: 'Phân tích',
    content: 'Báo cáo nghiên cứu thị trường phân tích xu hướng tiêu dùng trong lĩnh vực y tế.',
  },
  {
    id: 'doc-12',
    name: 'Noi-quy-phong-kham.txt',
    type: 'txt',
    size: '8 KB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-26T08:00:00Z',
    uploadedBy: 'Quản lý',
    content: 'Nội quy phòng khám quy định các hành vi chuẩn mực của nhân viên và bệnh nhân.',
  },
  {
    id: 'doc-13',
    name: 'Danh-sach-doi-tac-cung-ung.xlsx',
    type: 'xlsx',
    size: '1.5 MB',
    hubId: '3',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-26T11:00:00Z',
    uploadedBy: 'Mua hàng',
    content: 'Danh sách đối tác cung ứng vật tư y tế và trang thiết bị cho phòng khám.',
  },
  {
    id: 'doc-14',
    name: 'Huong-dan-ve-sinh-khu-trung.pdf',
    type: 'pdf',
    size: '2.8 MB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-27T13:45:00Z',
    uploadedBy: 'Kiểm soát nhiễm khuẩn',
    content: 'Hướng dẫn vệ sinh khử trùng đảm bảo môi trường y tế luôn sạch sẽ và an toàn.',
  },
  {
    id: 'doc-15',
    name: 'Quy-dinh-ve-quan-ly-ho-so-benh-an.docx',
    type: 'docx',
    size: '1.8 MB',
    hubId: '2',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-27T15:30:00Z',
    uploadedBy: 'Lưu trữ',
    content: 'Quy định về quản lý hồ sơ bệnh án giúp bảo mật và dễ dàng tra cứu thông tin bệnh nhân.',
  },
  {
    id: 'doc-16',
    name: 'Bao-cao-chat-luong-dich-vu-thang-3.pdf',
    type: 'pdf',
    size: '4.2 MB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-28T10:15:00Z',
    uploadedBy: 'CSKH',
    content: 'Báo cáo chất lượng dịch vụ tháng 3 đánh giá mức độ hài lòng của bệnh nhân.',
  },
  {
    id: 'doc-17',
    name: 'Ke-hoach-dao-tao-nhan-vien-Q2.docx',
    type: 'docx',
    size: '1.1 MB',
    hubId: '3',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-28T14:30:00Z',
    uploadedBy: 'Đào tạo',
    content: 'Kế hoạch đào tạo nhân viên quý 2 tập trung nâng cao kỹ năng chuyên môn và giao tiếp.',
  },
  {
    id: 'doc-18',
    name: 'Quy-trinh-xu-ly-rac-thai-y-te.pdf',
    type: 'pdf',
    size: '3.5 MB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-29T09:00:00Z',
    uploadedBy: 'Môi trường',
    content: 'Quy trình xử lý rác thải y tế tuân thủ các quy định về bảo vệ môi trường.',
  },
  {
    id: 'doc-19',
    name: 'Danh-muc-trang-thiet-bi-y-te.xlsx',
    type: 'xlsx',
    size: '5.8 MB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-29T11:45:00Z',
    uploadedBy: 'Kỹ thuật',
    content: 'Danh mục trang thiết bị y tế hiện có và tình trạng hoạt động của chúng.',
  },
  {
    id: 'doc-20',
    name: 'Huong-dan-su-dung-phan-mem-quan-ly.pdf',
    type: 'pdf',
    size: '10.2 MB',
    hubId: '3',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-30T15:00:00Z',
    uploadedBy: 'IT',
    content: 'Hướng dẫn sử dụng phần mềm quản lý phòng khám cho nhân viên mới.',
  },
  {
    id: 'doc-21',
    name: 'Quy-dinh-ve-trang-phuc-nhan-vien.docx',
    type: 'docx',
    size: '750 KB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-30T16:30:00Z',
    uploadedBy: 'Hành chính',
    content: 'Quy định về trang phục nhân viên nhằm tạo hình ảnh chuyên nghiệp cho phòng khám.',
  },
  {
    id: 'doc-22',
    name: 'Bao-cao-ket-qua-kham-suc-khoe-doan.pdf',
    type: 'pdf',
    size: '15.4 MB',
    hubId: '2',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-31T10:00:00Z',
    uploadedBy: 'Kinh doanh',
    content: 'Báo cáo kết quả khám sức khỏe đoàn cho các công ty đối tác.',
  },
  {
    id: 'doc-23',
    name: 'Ke-hoach-to-chuc-su-kien-1-5.pptx',
    type: 'pptx',
    size: '8.6 MB',
    hubId: '3',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-03-31T14:00:00Z',
    uploadedBy: 'Công đoàn',
    content: 'Kế hoạch tổ chức sự kiện ngày Quốc tế Lao động cho nhân viên.',
  },
  {
    id: 'doc-24',
    name: 'Quy-trinh-bao-tri-may-moc.docx',
    type: 'docx',
    size: '1.4 MB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-04-01T08:30:00Z',
    uploadedBy: 'Bảo trì',
    content: 'Quy trình bảo trì máy móc định kỳ giúp kéo dài tuổi thọ thiết bị.',
  },
  {
    id: 'doc-25',
    name: 'Danh-sach-nhan-vien-xuat-sac-thang-3.xlsx',
    type: 'xlsx',
    size: '45 KB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-04-01T11:00:00Z',
    uploadedBy: 'Thi đua',
    content: 'Danh sách nhân viên xuất sắc tháng 3 được khen thưởng.',
  },
  {
    id: 'doc-26',
    name: 'Huong-dan-phong-chay-chua-chay.pdf',
    type: 'pdf',
    size: '4.8 MB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-04-02T09:45:00Z',
    uploadedBy: 'An ninh',
    content: 'Hướng dẫn phòng cháy chữa cháy và các kỹ năng thoát hiểm cơ bản.',
  },
  {
    id: 'doc-27',
    name: 'Quy-dinh-ve-nghi-phep-va-le-tet.docx',
    type: 'docx',
    size: '1.2 MB',
    hubId: '3',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-04-02T14:15:00Z',
    uploadedBy: 'Nhân sự',
    content: 'Quy định về nghỉ phép và lễ tết cho nhân viên trong năm 2024.',
  },
  {
    id: 'doc-28',
    name: 'Bao-cao-su-dung-vat-tu-tieu-hao.pdf',
    type: 'pdf',
    size: '2.5 MB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-04-03T10:30:00Z',
    uploadedBy: 'Kho',
    content: 'Báo cáo sử dụng vật tư tiêu hao trong tháng 3.',
  },
  {
    id: 'doc-29',
    name: 'Ke-hoach-phat-trien-dich-vu-moi.docx',
    type: 'docx',
    size: '2.1 MB',
    hubId: '2',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-04-03T15:45:00Z',
    uploadedBy: 'Chiến lược',
    content: 'Kế hoạch phát triển dịch vụ mới nhằm đáp ứng nhu cầu ngày càng cao của bệnh nhân.',
  },
  {
    id: 'doc-30',
    name: 'Bien-ban-kiem-ke-tai-san-cuoi-nam.xlsx',
    type: 'xlsx',
    size: '3.4 MB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-04-04T09:00:00Z',
    uploadedBy: 'Tài sản',
    content: 'Biên bản kiểm kê tài sản cuối năm ghi lại tình trạng thực tế của các tài sản.',
  },
  {
    id: 'doc-31',
    name: 'Huong-dan-cham-soc-benh-nhan-sau-mo.pdf',
    type: 'pdf',
    size: '6.2 MB',
    hubId: '1',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-04-04T13:30:00Z',
    uploadedBy: 'Điều dưỡng',
    content: 'Hướng dẫn chăm sóc bệnh nhân sau mổ giúp bệnh nhân nhanh chóng hồi phục.',
  },
  {
    id: 'doc-32',
    name: 'Quy-trinh-tiep-nhan-khieu-nai.docx',
    type: 'docx',
    size: '1.1 MB',
    hubId: '2',
    status: 'completed',
    progress: 100,
    uploadedAt: '2024-04-05T10:45:00Z',
    uploadedBy: 'Pháp chế',
    content: 'Quy trình tiếp nhận khiếu nại đảm bảo mọi ý kiến của khách hàng đều được lắng nghe và giải quyết.',
  },
];
